version: '3.3'

services:
  app:
    build: ./
    container_name: flask
    environment:
      - POSTGRESQL_URL=postgresql://worker:worker@postgres_db/app
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:11
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - ./posgres:/var/lib
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=worker
      - POSTGRES_PASSWORD=worker
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worker -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
#    name: db_data
    driver: local
    